
# Language support configuration.
# See the languages documentation: https://docs.helix-editor.com/master/languages.html

use-grammars = { except = [ "wren", "gemini" ] }

[language-server]

 purescript-language-server = { command = "purescript-language-server", args = ["--stdio"] }


[[language]]
name = "purescript"
scope = "source.purescript"
injection-regex = "purescript"
file-types = ["purs"]
roots = ["spago.yaml", "spago.dhall", "bower.json"]
comment-token = "--"
block-comment-tokens = { start = "{-", end = "-}" }
language-servers = [ "purescript-language-server" ]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "purs-tidy", args = ["format", "--indent", "4"] }
