
# Language support configuration.
# See the languages documentation: https://docs.helix-editor.com/master/languages.html
# reference: https://github.com/helix-editor/helix/blob/master/languages.toml

use-grammars = { except = [ "wren", "gemini" ] }

[language-server]

 purescript-language-server = { command = "purescript-language-server", args = ["--stdio"] }


[[language]]
name = "purescript"
scope = "source.purescript"
injection-regex = "purescript"
file-types = ["purs"]
roots = ["spago.yaml", "spago.dhall", "bower.json"]
comment-token = "--"
block-comment-tokens = { start = "{-", end = "-}" }
language-servers = [ "purescript-language-server" ]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "purs-tidy", args = ["format", "--indent", "4"] }

[language-server.clangd]
command = "clangd"
args = [
    # "--header-insertion=never",      # Don't touch my code
    "--complete-all-scopes=false",   # Only suggest what I've included
    # "--background-index=false",      # Stop scanning files in the background
]

# This is the magic line: it kills the nagging, keeps the typing help
[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c", "h"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
# language-servers = [ { name = "clangd", except-features = ["diagnostics"] } ]
indent = { tab-width = 4, unit = "    " }

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { console = "internalConsole", program = "{0}" }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { console = "internalConsole", pid = "{0}" }

[[language.debugger.templates]]
name = "gdbserver attach"
request = "attach"
completion = [ { name = "lldb connect url", default = "connect://localhost:3333" }, { name = "file", completion = "filename" }, "pid" ]
args = { console = "internalConsole", attachCommands = [ "platform select remote-gdb-server", "platform connect {0}", "file {1}", "attach {2}" ] }

[[grammar]]
name = "c"
source = { git = "https://github.com/tree-sitter/tree-sitter-c", rev = "7fa1be1b694b6e763686793d97da01f36a0e5c12" }
